### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by radiumx3** [braseidon/steam-inventory-laravel#1]
4 months till last commit, no documentation ...

**Comment by radiumx3** [comment]
@braseidon ?!

**Comment by ryantology** [comment]
@radiumx3 ![Use the Source Luke](http://blog.codinghorror.com/content/images/uploads/2012/04/6a0120a85dcdae970b016765373659970b-800wi.jpg)

Or make a PR, or have a specific question.

**Comment by unr** [comment]
:+1:

**Comment by radiumx3** [comment]
@ryantology What's the purpose to put a lib public if no documentation provided at all ? Is this github or i'm lost maybe ? >.>

**Comment by ryantology** [comment]
@radiumx3 GitHub is a place to store `code`. If you have a question about how something works feel free to post it. I had no problem getting this library working. I am extremely appreciative of the work that was put in by @braseidon without warranty, or payment. 

Welcome to OpenSource. Feel free to contribute and create a Pull request.

Or like I did fork the repo and improve it.

**Comment by ryantology** [comment]
In all honesty. This is how you use it:

In your controller add:
`use Braseidon\SteamInventory\SteamInventory;`

Then in the controller declare your methods like

``` php
public function index(SteamInventory $inventory)
{
    return $inventory;
}
```

This is how most service provider stuff works. If you are looking to use this lib I would suggest taking a look at my fork. I combined the data that is returned from steam into a single collection rather than separate collections for inventory, descriptions, currency.

**Comment by radiumx3** [comment]
@ryantology  i'll take a look with that snippet, thanks for this usefull piece of info ;)

**Comment by braseidon** [comment]
@radiumx3 There's only one file you need to look at and you can see all of the available methods:

https://github.com/braseidon/steam-inventory-laravel/blob/master/src/SteamInventory.php

Sorry about no documentation yet but I am busy with projects :) I never had any interest in these packages so I never really felt motivated to write documentation

**Comment by braseidon** [comment]
Thanks @ryantology for helping explaining things
